# Rails secret token
secret_token: ''

# Environment dependant settings
development:
  # Mailer
  host: 'localhost:3000'
  # Omniauth
  twitter_key: ''
  twitter_secret: ''
  github_key: ''
  github_secret: ''

production:
  # Mailer
  host: 'conf.nu'
  # Omniauth
  twitter_key: ''
  twitter_secret: ''
  github_key: ''
  github_secret: ''

test:
  host: 'test.local'
