# Rails secret token
secret_token: ''

# AWS
aws_access_key_id: ''
aws_secret_access_key: ''

# HTTP Authentication
http_authentication_user: ''
http_authentication_password: ''

# Mailer
gmail_username: ''
gmail_password: ''

# Environment dependant settings
development:
  # Mailer
  host: ''
  # AWS
  aws_s3_bucket: ''
  # Omniauth
  twitter_key: ''
  twitter_secret: ''
  github_key: ''
  github_secret: ''

production:
  # Mailer
  host: ''
  # AWS
  aws_s3_bucket: ''
  # Omniauth
  twitter_key: ''
  twitter_secret: ''
  github_key: ''
  github_secret: ''

test:
  host: ''
