development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode
  database: confnu_development

test:
  <<: *default
  database: confnu_test
  min_messages: warning

production:
  <<: *default
  database:
  username:
  password:

staging:
  <<: *default
  database:
  username:
  password:
