# Rails secret key
secret_key_base:

# AWS
aws_access_key_id:
aws_secret_access_key:

# Environment dependant settings
development:
  # Server names
  confnu_server_names:
  # Mailer
  host:
  # AWS
  aws_s3_bucket:
  # Omniauth
  twitter_key:
  twitter_secret:
  github_key:
  github_secret:
  # Mailer
  gmail_username:
  gmail_password:

staging:
  # Server names
  confnu_server_names:
  # Mailer
  host:
  # AWS
  aws_s3_bucket:
  # Omniauth
  twitter_key:
  twitter_secret:
  github_key:
  github_secret:
  # Mailer
  gmail_username:
  gmail_password:

production:
  # Server names
  confnu_server_names:
  # Mailer
  host:
  # AWS
  aws_s3_bucket:
  # Omniauth
  twitter_key:
  twitter_secret:
  github_key:
  github_secret:
  # Mailer
  gmail_username:
  gmail_password:
